### ISSUE TITLE
Bug for code generator?

### ISSUE THREAD

**Issue by exshonda** [HirokiNakahara/GUINNESS#1]
In the tutorial, the output of the integer convolution called on layer 0 is called as 128.

            int_conv2d_layer<bit_64, bit_128, 64, 128, 48, 48>
            ( in_img, fb_tmp, conv0W, b0_BNFb);

It should be 64 from the weight and bias memory width.

// weight memory -----------------------------------------------------------
ap_int<3>  conv0W[64][3*3];
ap_int<64>  conv1W[128][3*3];
ap_int<128>  conv2W[128][3*3];
ap_int<1>  fc0W[3][128];

// bias memory ------------------------------------------------------------
ap_int<20> b0_BNFb[64];
ap_int<16> b1_BNFb[128];
ap_int<16> b2_BNFb[128];
ap_int<16> b3_BNFb[3];

**Comment by HirokiNakahara** [comment]
Thank you very much! I fixed the C++ code generator.

**Comment by exshonda** [comment]
Thank you! 
I will check after  upgrading Python to v 3.
