### ISSUE TITLE
yolov2 on zcu102

### ISSUE THREAD

**Issue by hyw505** [HirokiNakahara/GUINNESS#11]
Hello, I have seen your  demonstrate  of yolov2 on zcu102 .  Would you like to share the detail or code for study?

**Comment by SGHSMITH** [comment]
Hi, I have seen the demonstration of pedestrian detection using  yolov2 on zcu102 . could you please share the details or code...?

**Comment by HirokiNakahara** [comment]
Sorry, this version is just a trial version. In the future, I will make another repository which includes YOLOv2 with sparseness and low-bit precision training code.
