### ISSUE TITLE
Problems in SDx build

### ISSUE THREAD

**Issue by Boshne** [HirokiNakahara/GUINNESS#4]

**Comment by BobWaseda** [comment]
Thanks for your consideration.

**Comment by BobWaseda** [comment]
install g++-multilib

**Comment by BobWaseda** [comment]
Then
Generating data motion network
ERROR: Linking globals named 'main': symbol multiply defined!
ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling '/home/bob/xilinx/SDx/2017.2/bin/llvm-link -o /home/bob/workspace/guinness_tut1_v1/Debug/_sds/.llvm/sds_all.o /home/bob/workspace/guinness_tut1_v1/Debug/_sds/.llvm/./src/cnn.s /home/bob/workspace/guinness_tut1_v1/Debug/_sds/.llvm/./src/main.s /home/bob/workspace/guinness_tut1_v1/Debug/_sds/.llvm/./src/socket_main.s'
sds++ log file saved as /home/bob/workspace/guinness_tut1_v1/Debug/_sds/reports/sds.log
ERROR: [SdsCompiler 83-5004] Build failed

makefile:45: recipe for target 'guinness_tut1_v1.so' failed
make: *** [guinness_tut1_v1.so] Error 1
