### ISSUE TITLE
How to use train data and label

### ISSUE THREAD

**Issue by Sunao-Furukawa** [HirokiNakahara/GUINNESS#5]
Hello.
Deep Learning I am a beginner.
I made it in mnist.py of deep-learning-from-scratch,
I have mnist.pkl, but label and image are packaged together.
In GUINNESS it seems that it is necessary to make DATA and LABEL separately,
I examined various things, but it will not work.
Please tell me how to divide DATA and LABEL successfully with mnist.

**Comment by HirokiNakahara** [comment]
Read the following site to generate MNIST images:
http://tensorflowz.com/tensorflow/mnist/convert-to-image/mnist-convert-jpg.html

Next, you store each numbered image to different folder, then prepare a "list.txt" file and run "gen_image_training_data.py".
