### ISSUE TITLE
ERROR: application performed illegal memory access and is being terminated

### ISSUE THREAD

**Issue by ninfueng** [HirokiNakahara/GUINNESS#6]
Hello, I had an error from the step number 6 in your tutorial. The error comes from when I input
_./guinness_tut1_v1.elf (my ip) 10050_  into the terminal which connected with FPGA(ZCU102) 
The complier error is as below.
> load weights
b0_BNFb.txt
CANNOT OPEN
ERROR: application performed illegal memory access and is being terminated

Do you have any suggestion for solving this problem?

**Comment by HirokiNakahara** [comment]
Did you store "b0_BNFb.txt" to the SD-card? Initially, it loads the pre-trained weight, which is a text file (.txt). Please check the contents of the SD-card.

**Comment by ninfueng** [comment]
Thank you for responding. From your suggestion, after I put the pre-train weights(.txt files) into the SD-card, I success to solve the problem (CANNOT OPEN). However, after I push the space key into the image view window, I found the compiler error as below.
```
load weights
b0_BNFb.txt
b1_BNFb.txt
b2_BNFb.txt
b3_BNFb.txt
conv0W.txt
conv1W.txt
conv2W.txt
fc0W.txt
setup... 
[INFO] IPADR=MY IP PORT=10050
Warning! Bitsize mismach for ap_[u]int |= ap_[u]int.
Warning! Bitsize mismach for ap_[u]int |= ap_[u]int.
Warning! Bitsize mismach for ap_[u]int |= ap_[u]int.
Warning! Bitsize mismach for ap_[u]int |= ap_[u]int.
Warning! Bitsize mismach for ap_[u]int |= ap_[u]int.
Warning! Bitsize mismach for ap_[u]int |= ap_[u]int.
```

**Comment by HirokiNakahara** [comment]
Hi, what is your SDSoC version? I think 2017.2 does not show these messages, please, try by using 2017.2 not use 2017.4. thank you.

**Comment by saitoh-synkom** [comment]
> Warning! Bitsize mismach for ap_[u]int |= ap_[u]int.

This could be resolved by modify this line

https://github.com/HirokiNakahara/GUINNESS/blob/6bd4b05470f8d54b6c24f1ad965ec5bb46f8aa2a/template_cpp_r7_main.cpp#L100

as following:

```
tmp |= (ap_int<64>)( pixel & 0xFFFFF);
```

**Comment by ninfueng** [comment]
Sorry for late responding. I tried with SDSoC 2017.2, the problem was solved. 
Thank @HirokiNakahara and @saitoh-synkom for helping.
