### ISSUE TITLE
Typo in guinness.py 

### ISSUE THREAD

**Issue by xiemark** [HirokiNakahara/GUINNESS#8]
guinness.py
from line 227 to 232
fpgaboard = QtGui.QLabel('Target FPGA Board')
        self.combo2 = QtGui.QComboBox()
        self.combo2.addItem("zed")
        self.combo2.addItem("zybo")
        self.combo2.addItem("vc702")
        self.combo2.addItem("zcu102")

In line 231, "self.combo2.addItem("vc702")" should be "self.combo2.addItem("zc702")"
It is a typo.

**Comment by HirokiNakahara** [comment]
Thanks! I modified it.
