### ISSUE TITLE
A Lightweight YOLOv2 - training 

### ISSUE THREAD

**Issue by ghimiredhikura** [HirokiNakahara/GUINNESS#9]
Hello @HirokiNakahara,

Thank you for the wonderful work. 
I am trying to train the similar network as yours: [https://dl.acm.org/citation.cfm?id=3174266](https://dl.acm.org/citation.cfm?id=3174266). 
But I only want to generate the training weights (no FPGA). As this repo is not the final version source of the paper above, can you please give me some instructions for training darknet19 like network. 

Best,
Deepak

**Comment by HirokiNakahara** [comment]
This version is just "trial" not professional version, which is released to vendors.

Thanks,
Hiroki
